# Generated by Django 3.0.14 on 2021-04-17 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0002_error'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={'verbose_name': 'Аккаунты', 'verbose_name_plural': 'Аккаунты'},
        ),
        migrations.AlterField(
            model_name='myuser',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scraping.City', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scraping.Language', verbose_name='Язык'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='send_email',
            field=models.BooleanField(default=True, verbose_name='Почта'),
        ),
    ]
